# Generated by Django 5.2.1 on 2025-05-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Paid', 'Paid'), ('Voided', 'Voided')], max_length=20),
        ),
    ]
